//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BruteForceHashSearch.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BruteForceHashSearch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quiet
        ///qui
        ///bacteria
        ///parasite
        ///metal
        ///metalic
        ///tension
        ///1080
        ///10th
        ///1st
        ///neck
        ///2
        ///2nd
        ///3rd
        ///4th
        ///5th
        ///6th
        ///7th
        ///8th
        ///9th
        ///a
        ///a&apos;
        ///a&apos;s
        ///a/c
        ///a1
        ///aa
        ///aaa
        ///aah
        ///aahed
        ///aahing
        ///aahs
        ///aal
        ///aalii
        ///aaliis
        ///aals
        ///aam
        ///aardvark
        ///aardvarks
        ///aardwolf
        ///aardwolves
        ///aargh
        ///aaron
        ///aaronic
        ///aarrgh
        ///aarrghh
        ///aas
        ///aasvogel
        ///aasvogels
        ///ab
        ///aba
        ///abac
        ///abaca
        ///abacas
        ///abacate
        ///abacaxi
        ///abacay
        ///abaci
        ///abacinate
        ///abacination
        ///abacisci
        ///abaciscus
        ///abacist
        ///aback
        ///abacli
        ///abacot
        ///abacterial
        ///abactinal
        ///abactinally
        ///abaction
        ///abactor
        ///abaculi
        ///abaculus
        ///abacus
        ///abacuses
        ///abada
        ///abaddon
        ///abadejo
        ///abadengo
        ///abad [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dictionary {
            get {
                return ResourceManager.GetString("Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eff
        ///Null
        ///qui
        ///qui0
        ///qui1
        ///wmuwrp01
        ///L
        ///R
        ///eqit
        ///cam
        ///def
        ///eqit1
        ///eqit0
        ///main
        ///main0
        ///main1
        ///Tension
        ///TENSION
        ///body
        ///Parasite
        ///Metalic
        ///Main1
        ///Main
        ///Main0
        ///Eqit0
        ///Eqit1
        ///Def
        ///Cam
        ///Eqit
        ///Wmuwrp01
        ///wrp01
        ///Wrp01
        ///Wmu
        ///wmu
        ///Qui
        ///Qui1
        ///Qui0
        ///Quiet
        ///quiet
        ///wrp
        ///Wrp
        ///tension
        ///metalic
        ///Metalic
        ///METALIC
        ///QUI
        ///QUI0
        ///QUI1
        ///WMU
        ///CAM
        ///DEF
        ///EQIT
        ///mimesis
        ///mimetic
        ///Mimetic
        ///MIMETIC
        ///Mimesis
        ///MetalicBacteria
        ///Bacteria
        ///BACTERIA
        ///PARASITE
        ///Parasite
        ///_
        ///NULL
        ///Null
        ///null
        ///0
        ///1
        ///2
        ///3
        ///4
        ///5
        ///6
        ///7
        ///8
        ///9.
        /// </summary>
        internal static string GuessWords {
            get {
                return ResourceManager.GetString("GuessWords", resourceCulture);
            }
        }
    }
}
